"""empty message

Revision ID: 91be94c325c3
Revises: 486ca00eef38
Create Date: 2019-07-30 23:54:11.805366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91be94c325c3'
down_revision = '486ca00eef38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'client_secret',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.create_unique_constraint(None, 'client', ['client_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.alter_column('client', 'client_secret',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
